version: 1
disable_existing_loggers: false
formatters:
  standard:
    format: "%(asctime)s [%(levelname)s] %(name)s (%(filename)s:%(lineno)d): %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  json:
    class: "logging.Formatter"
    format: '{"timestamp": "%(asctime)s", "level": "%(levelname)s", "logger": "%(name)s", "message": "%(message)s"}'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout
loggers:
  app:
    level: INFO
    handlers: [console]
    propagate: false
  simulator:
    level: INFO
    handlers: [console]
    propagate: false
root:
  level: INFO
  handlers: [console]
